version: '3'
services:
  app:
    container_name: example-api
    restart: always
    build: .
    ports:
      - '4041:4041'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
